// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rag.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CypherQuery   string                 `protobuf:"bytes,1,opt,name=cypher_query,json=cypherQuery,proto3" json:"cypher_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetCypherQuery() string {
	if x != nil {
		return x.CypherQuery
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultsJson   string                 `protobuf:"bytes,1,opt,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetResultsJson() string {
	if x != nil {
		return x.ResultsJson
	}
	return ""
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultsJson   string                 `protobuf:"bytes,1,opt,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResultsJson() string {
	if x != nil {
		return x.ResultsJson
	}
	return ""
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SemanticSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterTags    []string               `protobuf:"bytes,3,rep,name=filter_tags,json=filterTags,proto3" json:"filter_tags,omitempty"`
	FilterPages   []string               `protobuf:"bytes,4,rep,name=filter_pages,json=filterPages,proto3" json:"filter_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SemanticSearchRequest) GetFilterTags() []string {
	if x != nil {
		return x.FilterTags
	}
	return nil
}

func (x *SemanticSearchRequest) GetFilterPages() []string {
	if x != nil {
		return x.FilterPages
	}
	return nil
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultsJson   string                 `protobuf:"bytes,1,opt,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{5}
}

func (x *SemanticSearchResponse) GetResultsJson() string {
	if x != nil {
		return x.ResultsJson
	}
	return ""
}

func (x *SemanticSearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SemanticSearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HybridSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterTags     []string               `protobuf:"bytes,3,rep,name=filter_tags,json=filterTags,proto3" json:"filter_tags,omitempty"`
	FilterPages    []string               `protobuf:"bytes,4,rep,name=filter_pages,json=filterPages,proto3" json:"filter_pages,omitempty"`
	FusionMethod   string                 `protobuf:"bytes,5,opt,name=fusion_method,json=fusionMethod,proto3" json:"fusion_method,omitempty"` // "rrf" or "weighted"
	SemanticWeight float32                `protobuf:"fixed32,6,opt,name=semantic_weight,json=semanticWeight,proto3" json:"semantic_weight,omitempty"`
	KeywordWeight  float32                `protobuf:"fixed32,7,opt,name=keyword_weight,json=keywordWeight,proto3" json:"keyword_weight,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{6}
}

func (x *HybridSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HybridSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HybridSearchRequest) GetFilterTags() []string {
	if x != nil {
		return x.FilterTags
	}
	return nil
}

func (x *HybridSearchRequest) GetFilterPages() []string {
	if x != nil {
		return x.FilterPages
	}
	return nil
}

func (x *HybridSearchRequest) GetFusionMethod() string {
	if x != nil {
		return x.FusionMethod
	}
	return ""
}

func (x *HybridSearchRequest) GetSemanticWeight() float32 {
	if x != nil {
		return x.SemanticWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetKeywordWeight() float32 {
	if x != nil {
		return x.KeywordWeight
	}
	return 0
}

type HybridSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultsJson   string                 `protobuf:"bytes,1,opt,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{7}
}

func (x *HybridSearchResponse) GetResultsJson() string {
	if x != nil {
		return x.ResultsJson
	}
	return ""
}

func (x *HybridSearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HybridSearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReadPage messages
type ReadPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageName      string                 `protobuf:"bytes,1,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPageRequest) Reset() {
	*x = ReadPageRequest{}
	mi := &file_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageRequest) ProtoMessage() {}

func (x *ReadPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageRequest.ProtoReflect.Descriptor instead.
func (*ReadPageRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{8}
}

func (x *ReadPageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

type ReadPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPageResponse) Reset() {
	*x = ReadPageResponse{}
	mi := &file_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageResponse) ProtoMessage() {}

func (x *ReadPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageResponse.ProtoReflect.Descriptor instead.
func (*ReadPageResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{9}
}

func (x *ReadPageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadPageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadPageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ProposeChange messages
type ProposeChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPage    string                 `protobuf:"bytes,1,opt,name=target_page,json=targetPage,proto3" json:"target_page,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ProposedBy    string                 `protobuf:"bytes,5,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"` // Identifier of the proposer (default: "claude-code")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeChangeRequest) Reset() {
	*x = ProposeChangeRequest{}
	mi := &file_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeChangeRequest) ProtoMessage() {}

func (x *ProposeChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeChangeRequest.ProtoReflect.Descriptor instead.
func (*ProposeChangeRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{10}
}

func (x *ProposeChangeRequest) GetTargetPage() string {
	if x != nil {
		return x.TargetPage
	}
	return ""
}

func (x *ProposeChangeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProposeChangeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposeChangeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProposeChangeRequest) GetProposedBy() string {
	if x != nil {
		return x.ProposedBy
	}
	return ""
}

type ProposeChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ProposalPath  string                 `protobuf:"bytes,3,opt,name=proposal_path,json=proposalPath,proto3" json:"proposal_path,omitempty"`
	IsNewPage     bool                   `protobuf:"varint,4,opt,name=is_new_page,json=isNewPage,proto3" json:"is_new_page,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeChangeResponse) Reset() {
	*x = ProposeChangeResponse{}
	mi := &file_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeChangeResponse) ProtoMessage() {}

func (x *ProposeChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeChangeResponse.ProtoReflect.Descriptor instead.
func (*ProposeChangeResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{11}
}

func (x *ProposeChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProposeChangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProposeChangeResponse) GetProposalPath() string {
	if x != nil {
		return x.ProposalPath
	}
	return ""
}

func (x *ProposeChangeResponse) GetIsNewPage() bool {
	if x != nil {
		return x.IsNewPage
	}
	return false
}

func (x *ProposeChangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListProposals messages
type ListProposalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "pending", "accepted", "rejected", or "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsRequest) Reset() {
	*x = ListProposalsRequest{}
	mi := &file_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsRequest) ProtoMessage() {}

func (x *ListProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsRequest.ProtoReflect.Descriptor instead.
func (*ListProposalsRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{12}
}

func (x *ListProposalsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProposalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TargetPage    string                 `protobuf:"bytes,2,opt,name=target_page,json=targetPage,proto3" json:"target_page,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsNewPage     bool                   `protobuf:"varint,6,opt,name=is_new_page,json=isNewPage,proto3" json:"is_new_page,omitempty"`
	ProposedBy    string                 `protobuf:"bytes,7,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalInfo) Reset() {
	*x = ProposalInfo{}
	mi := &file_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalInfo) ProtoMessage() {}

func (x *ProposalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalInfo.ProtoReflect.Descriptor instead.
func (*ProposalInfo) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{13}
}

func (x *ProposalInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProposalInfo) GetTargetPage() string {
	if x != nil {
		return x.TargetPage
	}
	return ""
}

func (x *ProposalInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProposalInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProposalInfo) GetIsNewPage() bool {
	if x != nil {
		return x.IsNewPage
	}
	return false
}

func (x *ProposalInfo) GetProposedBy() string {
	if x != nil {
		return x.ProposedBy
	}
	return ""
}

func (x *ProposalInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListProposalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Proposals     []*ProposalInfo        `protobuf:"bytes,4,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsResponse) Reset() {
	*x = ListProposalsResponse{}
	mi := &file_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsResponse) ProtoMessage() {}

func (x *ListProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsResponse.ProtoReflect.Descriptor instead.
func (*ListProposalsResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{14}
}

func (x *ListProposalsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListProposalsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListProposalsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListProposalsResponse) GetProposals() []*ProposalInfo {
	if x != nil {
		return x.Proposals
	}
	return nil
}

// WithdrawProposal messages
type WithdrawProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalPath  string                 `protobuf:"bytes,1,opt,name=proposal_path,json=proposalPath,proto3" json:"proposal_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawProposalRequest) Reset() {
	*x = WithdrawProposalRequest{}
	mi := &file_rag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawProposalRequest) ProtoMessage() {}

func (x *WithdrawProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawProposalRequest.ProtoReflect.Descriptor instead.
func (*WithdrawProposalRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{15}
}

func (x *WithdrawProposalRequest) GetProposalPath() string {
	if x != nil {
		return x.ProposalPath
	}
	return ""
}

type WithdrawProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawProposalResponse) Reset() {
	*x = WithdrawProposalResponse{}
	mi := &file_rag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawProposalResponse) ProtoMessage() {}

func (x *WithdrawProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawProposalResponse.ProtoReflect.Descriptor instead.
func (*WithdrawProposalResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{16}
}

func (x *WithdrawProposalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawProposalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WithdrawProposalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetFolderContext messages
type GetFolderContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderPath    string                 `protobuf:"bytes,1,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"` // Open WebUI folder path (e.g., "Projects/MyProject")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolderContextRequest) Reset() {
	*x = GetFolderContextRequest{}
	mi := &file_rag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolderContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderContextRequest) ProtoMessage() {}

func (x *GetFolderContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderContextRequest.ProtoReflect.Descriptor instead.
func (*GetFolderContextRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{17}
}

func (x *GetFolderContextRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

type GetFolderContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`                               // Whether a matching page was found
	PageName      string                 `protobuf:"bytes,4,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`          // Name of the matched page
	PageContent   string                 `protobuf:"bytes,5,opt,name=page_content,json=pageContent,proto3" json:"page_content,omitempty"` // Full content of the matched page
	FolderScope   string                 `protobuf:"bytes,6,opt,name=folder_scope,json=folderScope,proto3" json:"folder_scope,omitempty"` // Silverbullet folder to scope searches to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolderContextResponse) Reset() {
	*x = GetFolderContextResponse{}
	mi := &file_rag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolderContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderContextResponse) ProtoMessage() {}

func (x *GetFolderContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderContextResponse.ProtoReflect.Descriptor instead.
func (*GetFolderContextResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{18}
}

func (x *GetFolderContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFolderContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFolderContextResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFolderContextResponse) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *GetFolderContextResponse) GetPageContent() string {
	if x != nil {
		return x.PageContent
	}
	return ""
}

func (x *GetFolderContextResponse) GetFolderScope() string {
	if x != nil {
		return x.FolderScope
	}
	return ""
}

// GetProjectContext messages
type GetProjectContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubRemote  string                 `protobuf:"bytes,1,opt,name=github_remote,json=githubRemote,proto3" json:"github_remote,omitempty"` // GitHub repository in "owner/repo" format
	FolderPath    string                 `protobuf:"bytes,2,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`       // Folder path in Silverbullet space (e.g., "Projects/MyProject")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectContextRequest) Reset() {
	*x = GetProjectContextRequest{}
	mi := &file_rag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectContextRequest) ProtoMessage() {}

func (x *GetProjectContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectContextRequest.ProtoReflect.Descriptor instead.
func (*GetProjectContextRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{19}
}

func (x *GetProjectContextRequest) GetGithubRemote() string {
	if x != nil {
		return x.GithubRemote
	}
	return ""
}

func (x *GetProjectContextRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

type RelatedPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedPage) Reset() {
	*x = RelatedPage{}
	mi := &file_rag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedPage) ProtoMessage() {}

func (x *RelatedPage) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedPage.ProtoReflect.Descriptor instead.
func (*RelatedPage) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{20}
}

func (x *RelatedPage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelatedPage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ProjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`         // Relative path to project file
	Github        string                 `protobuf:"bytes,2,opt,name=github,proto3" json:"github,omitempty"`     // GitHub remote if set
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`         // Tags from frontmatter
	Concerns      []string               `protobuf:"bytes,4,rep,name=concerns,proto3" json:"concerns,omitempty"` // Concerns from frontmatter
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`   // Page content (frontmatter stripped)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	mi := &file_rag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{21}
}

func (x *ProjectInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ProjectInfo) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *ProjectInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProjectInfo) GetConcerns() []string {
	if x != nil {
		return x.Concerns
	}
	return nil
}

func (x *ProjectInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetProjectContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Project       *ProjectInfo           `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	RelatedPages  []*RelatedPage         `protobuf:"bytes,4,rep,name=related_pages,json=relatedPages,proto3" json:"related_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectContextResponse) Reset() {
	*x = GetProjectContextResponse{}
	mi := &file_rag_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectContextResponse) ProtoMessage() {}

func (x *GetProjectContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectContextResponse.ProtoReflect.Descriptor instead.
func (*GetProjectContextResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{22}
}

func (x *GetProjectContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProjectContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetProjectContextResponse) GetProject() *ProjectInfo {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GetProjectContextResponse) GetRelatedPages() []*RelatedPage {
	if x != nil {
		return x.RelatedPages
	}
	return nil
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x10silverbullet_rag\"1\n" +
	"\fQueryRequest\x12!\n" +
	"\fcypher_query\x18\x01 \x01(\tR\vcypherQuery\"b\n" +
	"\rQueryResponse\x12!\n" +
	"\fresults_json\x18\x01 \x01(\tR\vresultsJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"?\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"c\n" +
	"\x0eSearchResponse\x12!\n" +
	"\fresults_json\x18\x01 \x01(\tR\vresultsJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x87\x01\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vfilter_tags\x18\x03 \x03(\tR\n" +
	"filterTags\x12!\n" +
	"\ffilter_pages\x18\x04 \x03(\tR\vfilterPages\"k\n" +
	"\x16SemanticSearchResponse\x12!\n" +
	"\fresults_json\x18\x01 \x01(\tR\vresultsJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xfa\x01\n" +
	"\x13HybridSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vfilter_tags\x18\x03 \x03(\tR\n" +
	"filterTags\x12!\n" +
	"\ffilter_pages\x18\x04 \x03(\tR\vfilterPages\x12#\n" +
	"\rfusion_method\x18\x05 \x01(\tR\ffusionMethod\x12'\n" +
	"\x0fsemantic_weight\x18\x06 \x01(\x02R\x0esemanticWeight\x12%\n" +
	"\x0ekeyword_weight\x18\a \x01(\x02R\rkeywordWeight\"i\n" +
	"\x14HybridSearchResponse\x12!\n" +
	"\fresults_json\x18\x01 \x01(\tR\vresultsJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\x0fReadPageRequest\x12\x1b\n" +
	"\tpage_name\x18\x01 \x01(\tR\bpageName\"\\\n" +
	"\x10ReadPageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xaa\x01\n" +
	"\x14ProposeChangeRequest\x12\x1f\n" +
	"\vtarget_page\x18\x01 \x01(\tR\n" +
	"targetPage\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vproposed_by\x18\x05 \x01(\tR\n" +
	"proposedBy\"\xa6\x01\n" +
	"\x15ProposeChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rproposal_path\x18\x03 \x01(\tR\fproposalPath\x12\x1e\n" +
	"\vis_new_page\x18\x04 \x01(\bR\tisNewPage\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\".\n" +
	"\x14ListProposalsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xf3\x01\n" +
	"\fProposalInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vtarget_page\x18\x02 \x01(\tR\n" +
	"targetPage\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\vis_new_page\x18\x06 \x01(\bR\tisNewPage\x12\x1f\n" +
	"\vproposed_by\x18\a \x01(\tR\n" +
	"proposedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x9b\x01\n" +
	"\x15ListProposalsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12<\n" +
	"\tproposals\x18\x04 \x03(\v2\x1e.silverbullet_rag.ProposalInfoR\tproposals\">\n" +
	"\x17WithdrawProposalRequest\x12#\n" +
	"\rproposal_path\x18\x01 \x01(\tR\fproposalPath\"d\n" +
	"\x18WithdrawProposalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x17GetFolderContextRequest\x12\x1f\n" +
	"\vfolder_path\x18\x01 \x01(\tR\n" +
	"folderPath\"\xc3\x01\n" +
	"\x18GetFolderContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x1b\n" +
	"\tpage_name\x18\x04 \x01(\tR\bpageName\x12!\n" +
	"\fpage_content\x18\x05 \x01(\tR\vpageContent\x12!\n" +
	"\ffolder_scope\x18\x06 \x01(\tR\vfolderScope\"`\n" +
	"\x18GetProjectContextRequest\x12#\n" +
	"\rgithub_remote\x18\x01 \x01(\tR\fgithubRemote\x12\x1f\n" +
	"\vfolder_path\x18\x02 \x01(\tR\n" +
	"folderPath\"5\n" +
	"\vRelatedPage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x83\x01\n" +
	"\vProjectInfo\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x16\n" +
	"\x06github\x18\x02 \x01(\tR\x06github\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1a\n" +
	"\bconcerns\x18\x04 \x03(\tR\bconcerns\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"\xc8\x01\n" +
	"\x19GetProjectContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x127\n" +
	"\aproject\x18\x03 \x01(\v2\x1d.silverbullet_rag.ProjectInfoR\aproject\x12B\n" +
	"\rrelated_pages\x18\x04 \x03(\v2\x1d.silverbullet_rag.RelatedPageR\frelatedPages2\xc2\a\n" +
	"\n" +
	"RAGService\x12H\n" +
	"\x05Query\x12\x1e.silverbullet_rag.QueryRequest\x1a\x1f.silverbullet_rag.QueryResponse\x12K\n" +
	"\x06Search\x12\x1f.silverbullet_rag.SearchRequest\x1a .silverbullet_rag.SearchResponse\x12c\n" +
	"\x0eSemanticSearch\x12'.silverbullet_rag.SemanticSearchRequest\x1a(.silverbullet_rag.SemanticSearchResponse\x12]\n" +
	"\fHybridSearch\x12%.silverbullet_rag.HybridSearchRequest\x1a&.silverbullet_rag.HybridSearchResponse\x12Q\n" +
	"\bReadPage\x12!.silverbullet_rag.ReadPageRequest\x1a\".silverbullet_rag.ReadPageResponse\x12`\n" +
	"\rProposeChange\x12&.silverbullet_rag.ProposeChangeRequest\x1a'.silverbullet_rag.ProposeChangeResponse\x12`\n" +
	"\rListProposals\x12&.silverbullet_rag.ListProposalsRequest\x1a'.silverbullet_rag.ListProposalsResponse\x12i\n" +
	"\x10WithdrawProposal\x12).silverbullet_rag.WithdrawProposalRequest\x1a*.silverbullet_rag.WithdrawProposalResponse\x12i\n" +
	"\x10GetFolderContext\x12).silverbullet_rag.GetFolderContextRequest\x1a*.silverbullet_rag.GetFolderContextResponse\x12l\n" +
	"\x11GetProjectContext\x12*.silverbullet_rag.GetProjectContextRequest\x1a+.silverbullet_rag.GetProjectContextResponseB7Z5github.com/boblangley/silverbullet-rag/internal/protob\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_rag_proto_goTypes = []any{
	(*QueryRequest)(nil),              // 0: silverbullet_rag.QueryRequest
	(*QueryResponse)(nil),             // 1: silverbullet_rag.QueryResponse
	(*SearchRequest)(nil),             // 2: silverbullet_rag.SearchRequest
	(*SearchResponse)(nil),            // 3: silverbullet_rag.SearchResponse
	(*SemanticSearchRequest)(nil),     // 4: silverbullet_rag.SemanticSearchRequest
	(*SemanticSearchResponse)(nil),    // 5: silverbullet_rag.SemanticSearchResponse
	(*HybridSearchRequest)(nil),       // 6: silverbullet_rag.HybridSearchRequest
	(*HybridSearchResponse)(nil),      // 7: silverbullet_rag.HybridSearchResponse
	(*ReadPageRequest)(nil),           // 8: silverbullet_rag.ReadPageRequest
	(*ReadPageResponse)(nil),          // 9: silverbullet_rag.ReadPageResponse
	(*ProposeChangeRequest)(nil),      // 10: silverbullet_rag.ProposeChangeRequest
	(*ProposeChangeResponse)(nil),     // 11: silverbullet_rag.ProposeChangeResponse
	(*ListProposalsRequest)(nil),      // 12: silverbullet_rag.ListProposalsRequest
	(*ProposalInfo)(nil),              // 13: silverbullet_rag.ProposalInfo
	(*ListProposalsResponse)(nil),     // 14: silverbullet_rag.ListProposalsResponse
	(*WithdrawProposalRequest)(nil),   // 15: silverbullet_rag.WithdrawProposalRequest
	(*WithdrawProposalResponse)(nil),  // 16: silverbullet_rag.WithdrawProposalResponse
	(*GetFolderContextRequest)(nil),   // 17: silverbullet_rag.GetFolderContextRequest
	(*GetFolderContextResponse)(nil),  // 18: silverbullet_rag.GetFolderContextResponse
	(*GetProjectContextRequest)(nil),  // 19: silverbullet_rag.GetProjectContextRequest
	(*RelatedPage)(nil),               // 20: silverbullet_rag.RelatedPage
	(*ProjectInfo)(nil),               // 21: silverbullet_rag.ProjectInfo
	(*GetProjectContextResponse)(nil), // 22: silverbullet_rag.GetProjectContextResponse
}
var file_rag_proto_depIdxs = []int32{
	13, // 0: silverbullet_rag.ListProposalsResponse.proposals:type_name -> silverbullet_rag.ProposalInfo
	21, // 1: silverbullet_rag.GetProjectContextResponse.project:type_name -> silverbullet_rag.ProjectInfo
	20, // 2: silverbullet_rag.GetProjectContextResponse.related_pages:type_name -> silverbullet_rag.RelatedPage
	0,  // 3: silverbullet_rag.RAGService.Query:input_type -> silverbullet_rag.QueryRequest
	2,  // 4: silverbullet_rag.RAGService.Search:input_type -> silverbullet_rag.SearchRequest
	4,  // 5: silverbullet_rag.RAGService.SemanticSearch:input_type -> silverbullet_rag.SemanticSearchRequest
	6,  // 6: silverbullet_rag.RAGService.HybridSearch:input_type -> silverbullet_rag.HybridSearchRequest
	8,  // 7: silverbullet_rag.RAGService.ReadPage:input_type -> silverbullet_rag.ReadPageRequest
	10, // 8: silverbullet_rag.RAGService.ProposeChange:input_type -> silverbullet_rag.ProposeChangeRequest
	12, // 9: silverbullet_rag.RAGService.ListProposals:input_type -> silverbullet_rag.ListProposalsRequest
	15, // 10: silverbullet_rag.RAGService.WithdrawProposal:input_type -> silverbullet_rag.WithdrawProposalRequest
	17, // 11: silverbullet_rag.RAGService.GetFolderContext:input_type -> silverbullet_rag.GetFolderContextRequest
	19, // 12: silverbullet_rag.RAGService.GetProjectContext:input_type -> silverbullet_rag.GetProjectContextRequest
	1,  // 13: silverbullet_rag.RAGService.Query:output_type -> silverbullet_rag.QueryResponse
	3,  // 14: silverbullet_rag.RAGService.Search:output_type -> silverbullet_rag.SearchResponse
	5,  // 15: silverbullet_rag.RAGService.SemanticSearch:output_type -> silverbullet_rag.SemanticSearchResponse
	7,  // 16: silverbullet_rag.RAGService.HybridSearch:output_type -> silverbullet_rag.HybridSearchResponse
	9,  // 17: silverbullet_rag.RAGService.ReadPage:output_type -> silverbullet_rag.ReadPageResponse
	11, // 18: silverbullet_rag.RAGService.ProposeChange:output_type -> silverbullet_rag.ProposeChangeResponse
	14, // 19: silverbullet_rag.RAGService.ListProposals:output_type -> silverbullet_rag.ListProposalsResponse
	16, // 20: silverbullet_rag.RAGService.WithdrawProposal:output_type -> silverbullet_rag.WithdrawProposalResponse
	18, // 21: silverbullet_rag.RAGService.GetFolderContext:output_type -> silverbullet_rag.GetFolderContextResponse
	22, // 22: silverbullet_rag.RAGService.GetProjectContext:output_type -> silverbullet_rag.GetProjectContextResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
