// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: rag.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAGService_Query_FullMethodName             = "/silverbullet_rag.RAGService/Query"
	RAGService_Search_FullMethodName            = "/silverbullet_rag.RAGService/Search"
	RAGService_SemanticSearch_FullMethodName    = "/silverbullet_rag.RAGService/SemanticSearch"
	RAGService_HybridSearch_FullMethodName      = "/silverbullet_rag.RAGService/HybridSearch"
	RAGService_ReadPage_FullMethodName          = "/silverbullet_rag.RAGService/ReadPage"
	RAGService_ProposeChange_FullMethodName     = "/silverbullet_rag.RAGService/ProposeChange"
	RAGService_ListProposals_FullMethodName     = "/silverbullet_rag.RAGService/ListProposals"
	RAGService_WithdrawProposal_FullMethodName  = "/silverbullet_rag.RAGService/WithdrawProposal"
	RAGService_GetFolderContext_FullMethodName  = "/silverbullet_rag.RAGService/GetFolderContext"
	RAGService_GetProjectContext_FullMethodName = "/silverbullet_rag.RAGService/GetProjectContext"
)

// RAGServiceClient is the client API for RAGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RAG service for fast hooks integration
type RAGServiceClient interface {
	// Query the knowledge graph
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Search by keyword
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Semantic search using vector embeddings
	SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error)
	// Hybrid search combining keyword and semantic search
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// Read a page from the space
	ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*ReadPageResponse, error)
	// Propose a change to a page (creates a proposal for user review)
	ProposeChange(ctx context.Context, in *ProposeChangeRequest, opts ...grpc.CallOption) (*ProposeChangeResponse, error)
	// List change proposals by status
	ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsResponse, error)
	// Withdraw a pending proposal
	WithdrawProposal(ctx context.Context, in *WithdrawProposalRequest, opts ...grpc.CallOption) (*WithdrawProposalResponse, error)
	// Get context for an Open WebUI folder (finds pages with matching openwebui-folder frontmatter)
	GetFolderContext(ctx context.Context, in *GetFolderContextRequest, opts ...grpc.CallOption) (*GetFolderContextResponse, error)
	// Get project context by GitHub remote or folder path
	GetProjectContext(ctx context.Context, in *GetProjectContextRequest, opts ...grpc.CallOption) (*GetProjectContextResponse, error)
}

type rAGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAGServiceClient(cc grpc.ClientConnInterface) RAGServiceClient {
	return &rAGServiceClient{cc}
}

func (c *rAGServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, RAGService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RAGService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticSearchResponse)
	err := c.cc.Invoke(ctx, RAGService_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, RAGService_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*ReadPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPageResponse)
	err := c.cc.Invoke(ctx, RAGService_ReadPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) ProposeChange(ctx context.Context, in *ProposeChangeRequest, opts ...grpc.CallOption) (*ProposeChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeChangeResponse)
	err := c.cc.Invoke(ctx, RAGService_ProposeChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProposalsResponse)
	err := c.cc.Invoke(ctx, RAGService_ListProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) WithdrawProposal(ctx context.Context, in *WithdrawProposalRequest, opts ...grpc.CallOption) (*WithdrawProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawProposalResponse)
	err := c.cc.Invoke(ctx, RAGService_WithdrawProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) GetFolderContext(ctx context.Context, in *GetFolderContextRequest, opts ...grpc.CallOption) (*GetFolderContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFolderContextResponse)
	err := c.cc.Invoke(ctx, RAGService_GetFolderContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAGServiceClient) GetProjectContext(ctx context.Context, in *GetProjectContextRequest, opts ...grpc.CallOption) (*GetProjectContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectContextResponse)
	err := c.cc.Invoke(ctx, RAGService_GetProjectContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAGServiceServer is the server API for RAGService service.
// All implementations must embed UnimplementedRAGServiceServer
// for forward compatibility.
//
// RAG service for fast hooks integration
type RAGServiceServer interface {
	// Query the knowledge graph
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Search by keyword
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Semantic search using vector embeddings
	SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error)
	// Hybrid search combining keyword and semantic search
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// Read a page from the space
	ReadPage(context.Context, *ReadPageRequest) (*ReadPageResponse, error)
	// Propose a change to a page (creates a proposal for user review)
	ProposeChange(context.Context, *ProposeChangeRequest) (*ProposeChangeResponse, error)
	// List change proposals by status
	ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsResponse, error)
	// Withdraw a pending proposal
	WithdrawProposal(context.Context, *WithdrawProposalRequest) (*WithdrawProposalResponse, error)
	// Get context for an Open WebUI folder (finds pages with matching openwebui-folder frontmatter)
	GetFolderContext(context.Context, *GetFolderContextRequest) (*GetFolderContextResponse, error)
	// Get project context by GitHub remote or folder path
	GetProjectContext(context.Context, *GetProjectContextRequest) (*GetProjectContextResponse, error)
	mustEmbedUnimplementedRAGServiceServer()
}

// UnimplementedRAGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAGServiceServer struct{}

func (UnimplementedRAGServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRAGServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRAGServiceServer) SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedRAGServiceServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedRAGServiceServer) ReadPage(context.Context, *ReadPageRequest) (*ReadPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPage not implemented")
}
func (UnimplementedRAGServiceServer) ProposeChange(context.Context, *ProposeChangeRequest) (*ProposeChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeChange not implemented")
}
func (UnimplementedRAGServiceServer) ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProposals not implemented")
}
func (UnimplementedRAGServiceServer) WithdrawProposal(context.Context, *WithdrawProposalRequest) (*WithdrawProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawProposal not implemented")
}
func (UnimplementedRAGServiceServer) GetFolderContext(context.Context, *GetFolderContextRequest) (*GetFolderContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFolderContext not implemented")
}
func (UnimplementedRAGServiceServer) GetProjectContext(context.Context, *GetProjectContextRequest) (*GetProjectContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectContext not implemented")
}
func (UnimplementedRAGServiceServer) mustEmbedUnimplementedRAGServiceServer() {}
func (UnimplementedRAGServiceServer) testEmbeddedByValue()                    {}

// UnsafeRAGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAGServiceServer will
// result in compilation errors.
type UnsafeRAGServiceServer interface {
	mustEmbedUnimplementedRAGServiceServer()
}

func RegisterRAGServiceServer(s grpc.ServiceRegistrar, srv RAGServiceServer) {
	// If the following call panics, it indicates UnimplementedRAGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAGService_ServiceDesc, srv)
}

func _RAGService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).SemanticSearch(ctx, req.(*SemanticSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_ReadPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).ReadPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_ReadPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).ReadPage(ctx, req.(*ReadPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_ProposeChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).ProposeChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_ProposeChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).ProposeChange(ctx, req.(*ProposeChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_ListProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).ListProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_ListProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).ListProposals(ctx, req.(*ListProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_WithdrawProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).WithdrawProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_WithdrawProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).WithdrawProposal(ctx, req.(*WithdrawProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_GetFolderContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).GetFolderContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_GetFolderContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).GetFolderContext(ctx, req.(*GetFolderContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAGService_GetProjectContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGServiceServer).GetProjectContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGService_GetProjectContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGServiceServer).GetProjectContext(ctx, req.(*GetProjectContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RAGService_ServiceDesc is the grpc.ServiceDesc for RAGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silverbullet_rag.RAGService",
	HandlerType: (*RAGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _RAGService_Query_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RAGService_Search_Handler,
		},
		{
			MethodName: "SemanticSearch",
			Handler:    _RAGService_SemanticSearch_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _RAGService_HybridSearch_Handler,
		},
		{
			MethodName: "ReadPage",
			Handler:    _RAGService_ReadPage_Handler,
		},
		{
			MethodName: "ProposeChange",
			Handler:    _RAGService_ProposeChange_Handler,
		},
		{
			MethodName: "ListProposals",
			Handler:    _RAGService_ListProposals_Handler,
		},
		{
			MethodName: "WithdrawProposal",
			Handler:    _RAGService_WithdrawProposal_Handler,
		},
		{
			MethodName: "GetFolderContext",
			Handler:    _RAGService_GetFolderContext_Handler,
		},
		{
			MethodName: "GetProjectContext",
			Handler:    _RAGService_GetProjectContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag.proto",
}
