run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/boblangley/silverbullet-rag

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
    # Allow deprecated grpc.DialContext - marked as "will be supported throughout 1.x"
    - linters:
        - staticcheck
      text: "SA1019.*grpc\\.(DialContext|WithBlock)"
