# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in rag_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RAGServiceStub(object):
    """RAG service for fast hooks integration"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
            "/silverbullet_rag.RAGService/Query",
            request_serializer=rag__pb2.QueryRequest.SerializeToString,
            response_deserializer=rag__pb2.QueryResponse.FromString,
            _registered_method=True,
        )
        self.Search = channel.unary_unary(
            "/silverbullet_rag.RAGService/Search",
            request_serializer=rag__pb2.SearchRequest.SerializeToString,
            response_deserializer=rag__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.SemanticSearch = channel.unary_unary(
            "/silverbullet_rag.RAGService/SemanticSearch",
            request_serializer=rag__pb2.SemanticSearchRequest.SerializeToString,
            response_deserializer=rag__pb2.SemanticSearchResponse.FromString,
            _registered_method=True,
        )
        self.HybridSearch = channel.unary_unary(
            "/silverbullet_rag.RAGService/HybridSearch",
            request_serializer=rag__pb2.HybridSearchRequest.SerializeToString,
            response_deserializer=rag__pb2.HybridSearchResponse.FromString,
            _registered_method=True,
        )
        self.ReadPage = channel.unary_unary(
            "/silverbullet_rag.RAGService/ReadPage",
            request_serializer=rag__pb2.ReadPageRequest.SerializeToString,
            response_deserializer=rag__pb2.ReadPageResponse.FromString,
            _registered_method=True,
        )
        self.ProposeChange = channel.unary_unary(
            "/silverbullet_rag.RAGService/ProposeChange",
            request_serializer=rag__pb2.ProposeChangeRequest.SerializeToString,
            response_deserializer=rag__pb2.ProposeChangeResponse.FromString,
            _registered_method=True,
        )
        self.ListProposals = channel.unary_unary(
            "/silverbullet_rag.RAGService/ListProposals",
            request_serializer=rag__pb2.ListProposalsRequest.SerializeToString,
            response_deserializer=rag__pb2.ListProposalsResponse.FromString,
            _registered_method=True,
        )
        self.WithdrawProposal = channel.unary_unary(
            "/silverbullet_rag.RAGService/WithdrawProposal",
            request_serializer=rag__pb2.WithdrawProposalRequest.SerializeToString,
            response_deserializer=rag__pb2.WithdrawProposalResponse.FromString,
            _registered_method=True,
        )
        self.GetFolderContext = channel.unary_unary(
            "/silverbullet_rag.RAGService/GetFolderContext",
            request_serializer=rag__pb2.GetFolderContextRequest.SerializeToString,
            response_deserializer=rag__pb2.GetFolderContextResponse.FromString,
            _registered_method=True,
        )
        self.GetProjectContext = channel.unary_unary(
            "/silverbullet_rag.RAGService/GetProjectContext",
            request_serializer=rag__pb2.GetProjectContextRequest.SerializeToString,
            response_deserializer=rag__pb2.GetProjectContextResponse.FromString,
            _registered_method=True,
        )


class RAGServiceServicer(object):
    """RAG service for fast hooks integration"""

    def Query(self, request, context):
        """Query the knowledge graph"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Search(self, request, context):
        """Search by keyword"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SemanticSearch(self, request, context):
        """Semantic search using vector embeddings"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HybridSearch(self, request, context):
        """Hybrid search combining keyword and semantic search"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadPage(self, request, context):
        """Read a page from the space"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProposeChange(self, request, context):
        """Propose a change to a page (creates a proposal for user review)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListProposals(self, request, context):
        """List change proposals by status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WithdrawProposal(self, request, context):
        """Withdraw a pending proposal"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFolderContext(self, request, context):
        """Get context for an Open WebUI folder (finds pages with matching openwebui-folder frontmatter)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProjectContext(self, request, context):
        """Get project context by GitHub remote or folder path"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Query": grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=rag__pb2.QueryRequest.FromString,
            response_serializer=rag__pb2.QueryResponse.SerializeToString,
        ),
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=rag__pb2.SearchRequest.FromString,
            response_serializer=rag__pb2.SearchResponse.SerializeToString,
        ),
        "SemanticSearch": grpc.unary_unary_rpc_method_handler(
            servicer.SemanticSearch,
            request_deserializer=rag__pb2.SemanticSearchRequest.FromString,
            response_serializer=rag__pb2.SemanticSearchResponse.SerializeToString,
        ),
        "HybridSearch": grpc.unary_unary_rpc_method_handler(
            servicer.HybridSearch,
            request_deserializer=rag__pb2.HybridSearchRequest.FromString,
            response_serializer=rag__pb2.HybridSearchResponse.SerializeToString,
        ),
        "ReadPage": grpc.unary_unary_rpc_method_handler(
            servicer.ReadPage,
            request_deserializer=rag__pb2.ReadPageRequest.FromString,
            response_serializer=rag__pb2.ReadPageResponse.SerializeToString,
        ),
        "ProposeChange": grpc.unary_unary_rpc_method_handler(
            servicer.ProposeChange,
            request_deserializer=rag__pb2.ProposeChangeRequest.FromString,
            response_serializer=rag__pb2.ProposeChangeResponse.SerializeToString,
        ),
        "ListProposals": grpc.unary_unary_rpc_method_handler(
            servicer.ListProposals,
            request_deserializer=rag__pb2.ListProposalsRequest.FromString,
            response_serializer=rag__pb2.ListProposalsResponse.SerializeToString,
        ),
        "WithdrawProposal": grpc.unary_unary_rpc_method_handler(
            servicer.WithdrawProposal,
            request_deserializer=rag__pb2.WithdrawProposalRequest.FromString,
            response_serializer=rag__pb2.WithdrawProposalResponse.SerializeToString,
        ),
        "GetFolderContext": grpc.unary_unary_rpc_method_handler(
            servicer.GetFolderContext,
            request_deserializer=rag__pb2.GetFolderContextRequest.FromString,
            response_serializer=rag__pb2.GetFolderContextResponse.SerializeToString,
        ),
        "GetProjectContext": grpc.unary_unary_rpc_method_handler(
            servicer.GetProjectContext,
            request_deserializer=rag__pb2.GetProjectContextRequest.FromString,
            response_serializer=rag__pb2.GetProjectContextResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "silverbullet_rag.RAGService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "silverbullet_rag.RAGService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """RAG service for fast hooks integration"""

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/Query",
            rag__pb2.QueryRequest.SerializeToString,
            rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/Search",
            rag__pb2.SearchRequest.SerializeToString,
            rag__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SemanticSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/SemanticSearch",
            rag__pb2.SemanticSearchRequest.SerializeToString,
            rag__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HybridSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/HybridSearch",
            rag__pb2.HybridSearchRequest.SerializeToString,
            rag__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadPage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/ReadPage",
            rag__pb2.ReadPageRequest.SerializeToString,
            rag__pb2.ReadPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProposeChange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/ProposeChange",
            rag__pb2.ProposeChangeRequest.SerializeToString,
            rag__pb2.ProposeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListProposals(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/ListProposals",
            rag__pb2.ListProposalsRequest.SerializeToString,
            rag__pb2.ListProposalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WithdrawProposal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/WithdrawProposal",
            rag__pb2.WithdrawProposalRequest.SerializeToString,
            rag__pb2.WithdrawProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFolderContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/GetFolderContext",
            rag__pb2.GetFolderContextRequest.SerializeToString,
            rag__pb2.GetFolderContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProjectContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silverbullet_rag.RAGService/GetProjectContext",
            rag__pb2.GetProjectContextRequest.SerializeToString,
            rag__pb2.GetProjectContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
