# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub(object):
    """RAG service for fast hooks integration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/silverbullet_rag.RAGService/Query',
                request_serializer=rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/silverbullet_rag.RAGService/Search',
                request_serializer=rag__pb2.SearchRequest.SerializeToString,
                response_deserializer=rag__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/silverbullet_rag.RAGService/SemanticSearch',
                request_serializer=rag__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=rag__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/silverbullet_rag.RAGService/HybridSearch',
                request_serializer=rag__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=rag__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.UpdatePage = channel.unary_unary(
                '/silverbullet_rag.RAGService/UpdatePage',
                request_serializer=rag__pb2.UpdatePageRequest.SerializeToString,
                response_deserializer=rag__pb2.UpdatePageResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """RAG service for fast hooks integration
    """

    def Query(self, request, context):
        """Query the knowledge graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search by keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Semantic search using vector embeddings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Hybrid search combining keyword and semantic search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePage(self, request, context):
        """Update/reindex a page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=rag__pb2.QueryRequest.FromString,
                    response_serializer=rag__pb2.QueryResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=rag__pb2.SearchRequest.FromString,
                    response_serializer=rag__pb2.SearchResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=rag__pb2.SemanticSearchRequest.FromString,
                    response_serializer=rag__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=rag__pb2.HybridSearchRequest.FromString,
                    response_serializer=rag__pb2.HybridSearchResponse.SerializeToString,
            ),
            'UpdatePage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePage,
                    request_deserializer=rag__pb2.UpdatePageRequest.FromString,
                    response_serializer=rag__pb2.UpdatePageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silverbullet_rag.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('silverbullet_rag.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """RAG service for fast hooks integration
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silverbullet_rag.RAGService/Query',
            rag__pb2.QueryRequest.SerializeToString,
            rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silverbullet_rag.RAGService/Search',
            rag__pb2.SearchRequest.SerializeToString,
            rag__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silverbullet_rag.RAGService/SemanticSearch',
            rag__pb2.SemanticSearchRequest.SerializeToString,
            rag__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silverbullet_rag.RAGService/HybridSearch',
            rag__pb2.HybridSearchRequest.SerializeToString,
            rag__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silverbullet_rag.RAGService/UpdatePage',
            rag__pb2.UpdatePageRequest.SerializeToString,
            rag__pb2.UpdatePageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
