"""Knowledge graph schema definition for Cypher queries."""

GRAPH_SCHEMA = {
    "nodes": {
        "Page": {
            "description": "A markdown page in the Silverbullet space",
            "properties": ["name"],
            "example": "MATCH (p:Page {name: 'Projects/MyProject'}) RETURN p",
        },
        "Chunk": {
            "description": "A section of a page (split by headers)",
            "properties": [
                "id",
                "file_path",
                "header",
                "content",
                "frontmatter",
            ],
            "example": "MATCH (c:Chunk) WHERE c.content CONTAINS 'search term' RETURN c",
        },
        "Tag": {
            "description": "A hashtag used in pages",
            "properties": ["name"],
            "example": "MATCH (t:Tag {name: 'project'}) RETURN t",
        },
        "Folder": {
            "description": "A folder in the space hierarchy",
            "properties": ["path", "name"],
            "example": "MATCH (f:Folder {path: 'Projects'}) RETURN f",
        },
        "Attribute": {
            "description": "An inline attribute [key:: value]",
            "properties": ["id", "name", "value"],
            "example": "MATCH (a:Attribute {name: 'status'}) RETURN a",
        },
        "DataBlock": {
            "description": "A YAML data block with structured data",
            "properties": ["id", "tag", "data", "file_path"],
            "example": "MATCH (d:DataBlock {tag: 'task'}) RETURN d",
        },
    },
    "relationships": [
        {
            "type": "HAS_CHUNK",
            "from": "Page",
            "to": "Chunk",
            "properties": ["chunk_order"],
            "description": "Page contains chunks in order",
            "example": "MATCH (p:Page)-[r:HAS_CHUNK]->(c:Chunk) RETURN c ORDER BY r.chunk_order",
        },
        {
            "type": "PAGE_LINKS_TO",
            "from": "Page",
            "to": "Page",
            "properties": [],
            "description": "Page links to another page (derived from wikilinks)",
            "example": "MATCH (p:Page {name: 'Index'})-[:PAGE_LINKS_TO]->(linked:Page) RETURN linked",
        },
        {
            "type": "LINKS_TO",
            "from": "Chunk",
            "to": "Page",
            "properties": [],
            "description": "Chunk contains a wikilink to a page",
            "example": "MATCH (c:Chunk)-[:LINKS_TO]->(p:Page) RETURN c, p",
        },
        {
            "type": "TAGGED",
            "from": "Chunk",
            "to": "Tag",
            "properties": [],
            "description": "Chunk has a hashtag",
            "example": "MATCH (c:Chunk)-[:TAGGED]->(t:Tag {name: 'important'}) RETURN c",
        },
        {
            "type": "EMBEDS",
            "from": "Chunk",
            "to": "Page",
            "properties": ["header"],
            "description": "Chunk transcludes/embeds another page",
            "example": "MATCH (c:Chunk)-[r:EMBEDS]->(p:Page) RETURN c, p, r.header",
        },
        {
            "type": "HAS_ATTRIBUTE",
            "from": "Chunk",
            "to": "Attribute",
            "properties": [],
            "description": "Chunk contains an inline attribute",
            "example": "MATCH (c:Chunk)-[:HAS_ATTRIBUTE]->(a:Attribute {name: 'due'}) RETURN c, a.value",
        },
        {
            "type": "HAS_DATA_BLOCK",
            "from": "Chunk",
            "to": "DataBlock",
            "properties": [],
            "description": "Chunk contains a data block",
            "example": "MATCH (c:Chunk)-[:HAS_DATA_BLOCK]->(d:DataBlock) RETURN d",
        },
        {
            "type": "DATA_TAGGED",
            "from": "DataBlock",
            "to": "Tag",
            "properties": [],
            "description": "DataBlock is tagged with its block type",
            "example": "MATCH (d:DataBlock)-[:DATA_TAGGED]->(t:Tag {name: 'task'}) RETURN d",
        },
        {
            "type": "IN_FOLDER",
            "from": "Chunk",
            "to": "Folder",
            "properties": [],
            "description": "Chunk belongs to a folder",
            "example": "MATCH (c:Chunk)-[:IN_FOLDER]->(f:Folder {path: 'Projects'}) RETURN c",
        },
        {
            "type": "CONTAINS",
            "from": "Folder",
            "to": "Folder",
            "properties": [],
            "description": "Folder contains a subfolder",
            "example": "MATCH (f:Folder {path: 'Projects'})-[:CONTAINS]->(sub:Folder) RETURN sub",
        },
        {
            "type": "FOLDER_CONTAINS_PAGE",
            "from": "Folder",
            "to": "Page",
            "properties": [],
            "description": "Folder contains a page",
            "example": "MATCH (f:Folder)-[:FOLDER_CONTAINS_PAGE]->(p:Page) RETURN p",
        },
    ],
    "common_patterns": [
        {
            "name": "Find backlinks",
            "description": "Find all pages that link to a specific page",
            "query": "MATCH (source:Page)-[:PAGE_LINKS_TO]->(target:Page {name: $page_name}) RETURN source.name",
        },
        {
            "name": "Get page content",
            "description": "Get all chunks of a page in order",
            "query": "MATCH (p:Page {name: $page_name})-[r:HAS_CHUNK]->(c:Chunk) RETURN c.content ORDER BY r.chunk_order",
        },
        {
            "name": "Find pages by tag",
            "description": "Find all pages containing a specific tag",
            "query": "MATCH (p:Page)-[:HAS_CHUNK]->(c:Chunk)-[:TAGGED]->(t:Tag {name: $tag_name}) RETURN DISTINCT p.name",
        },
    ],
}
